#!/bin/bash

team=$1
image=$2
version=$3

if [ -z "$team" ]; then
    echo "Missing team argument" 2>&1
    exit 1
fi

if [ -z "$image" ]; then
    echo "Missing image argument" 2>&1
    exit 1
fi

if [ -z "$version" ]; then
    echo "Missing version argument" 2>&1
    exit 1
fi

PATH="/registry-data/docker/registry/v2/repositories/$team/$image/_manifests/tags/$version/"

if [ ! -d $PATH ]; then
    echo "Version does not exist" 2>&1
    exit 1
fi

/bin/rm -rf $PATH

if [ $? -eq 0 ]; then
    echo "Successfully deleted $team/$image:$version"
else
    echo "There was an error deleting $team/$image:$version" 2>&1
    exit 1
fi
