authenticator:
    image: na.cumulusrepo.com/cumulus_repo/authenticator
    environment:
        - CLOUDANT_ACCOUNT=${CLOUDANT_ACCOUNT}
        - CLOUDANT_PASSWORD=${CLOUDANT_PASSWORD}
coordinator:
    image: na.cumulusrepo.com/cumulus_repo/coordinator
    environment:
        - SERVICES=${SERVICES}
        - THISNODE=${THISNODE}
        - GEO=${GEO}
        - DOMAIN=${DOMAIN}
        - DEBUG=${DEBUG}
        - CLOUDANT_ACCOUNT=${CLOUDANT_ACCOUNT}
        - CLOUDANT_PASSWORD=${CLOUDANT_PASSWORD}
    links:
        - authenticator
        - registry_adapter
        - repo_adapter
registry:
    image: registry:2.5
    volumes:
        - /dockervolumes/registry-data/:/var/lib/registry/
    environment:
        - REGISTRY_STORAGE_DELETE_ENABLED=true
docker:
    image: docker:1.12.0-dind
    privileged: true
    command: "--insecure-registry registry:5000"
    links:
        - registry
registry_adapter:
    image: na.cumulusrepo.com/cumulus_repo/registry/adapter
    environment:
        - DOCKER_HOST=tcp://docker:2375
        - CLOUDANT_ACCOUNT=${CLOUDANT_ACCOUNT}
        - CLOUDANT_PASSWORD=${CLOUDANT_PASSWORD}
    links:
        - registry
        - docker
    volumes:
        - /dockervolumes/registry-data/:/registry-data/
repo:
    image: na.cumulusrepo.com/cumulus_repo/repo/nginx
    ports:
        - "443:9090"
    volumes:
        - /dockervolumes/ssl/:/ssl/
        - /dockervolumes/asset-data/:/var/asset-data/
    environment:
        - TZ=${TZ}
    links:
        - authenticator
        - repo_adapter
        - registry
        - coordinator
repo_adapter:
    image: na.cumulusrepo.com/cumulus_repo/repo/node
    volumes:
        - /dockervolumes/ssl/:/ssl/
        - /dockervolumes/asset-data/:/var/asset-data/
    environment:
        - CLOUDANT_ACCOUNT=${CLOUDANT_ACCOUNT}
        - CLOUDANT_PASSWORD=${CLOUDANT_PASSWORD}
    links:
        - authenticator
